
services:
  backend:
    build:
      context: ./backend  # Adjust the path to your backend folder
    image: manikanta455/food-backend:latest
    ports:
      - "5000:5000"
    volumes:
      - ./backend/donations.json:/app/donations.json  # Mount donations.json file
    networks:
      - food-network
  frontend:
    build:
      context: ./frontend  # Adjust the path to your frontend folder
    image: manikanta455/food-frontend:latest
    ports:
      - "8080:8080"
    networks:
      - food-network

networks:
  food-network:
    driver: overlay
    attachable: true

